import { PrettierConfig } from '@beemo/driver-prettier';

const config: PrettierConfig = {
  ignore: [
    '**/dist/*',
    '**/node_modules/*',
    '**/coverage/*',
    '**/.eslintrc.js',
    '**/.eslintrc.js',
    '**/prettier.config.js',
    '**/.linaria-cache/*',
    'lerna.json',
    'babel.config.js',
    'jest.config.js',
    // this folder is auto-generated by Docusaurus
    'packages/goji.js.org/website/*',
  ],
  arrowParens: 'avoid',
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  proseWrap: 'always',
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  overrides: [
    {
      files: '.babelrc',
      options: {
        parser: 'json',
      },
    },
    {
      files: '.prettierrc',
      options: {
        parser: 'json',
      },
    },
  ],
};

export default config;
